### ISSUE TITLE
Trying to get it working on Windows

### ISSUE THREAD

**Issue by NolenBrolen** [chengzeyi/stable-fast#72]
I've been trying to get it to work on Windows, but I'm currently stuck at this import error of some DLL file it seems. Does anyone know how to fix this issue, or some tips to try and get it working on Windows? 

```
Traceback (most recent call last):
  File "C:\Users\USER\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_stable_fast\__init__.py", line 1, in <module>    from .node import ApplyStableFastUnet
  File "C:\Users\USER\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 2, in <module>
    from sfast.compilers.stable_diffusion_pipeline_compiler import CompilationConfig
  File "C:\Users\USER\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sfast\__init__.py", line 23, in <module>
    import sfast._C as _C
ImportError: DLL load failed while importing _C: The specified module could not be found.

Cannot import C:\Users\USER\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_stable_fast module for custom nodes: DLL load failed while importing _C: The specified module could not be found.
```

**Comment by chengzeyi** [comment]
> I've been trying to get it to work on Windows, but I'm currently stuck at this import error of some DLL file it seems. Does anyone know how to fix this issue, or some tips to try and get it working on Windows?
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\USER\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1800, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\USER\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_stable_fast\__init__.py", line 1, in <module>    from .node import ApplyStableFastUnet
>   File "C:\Users\USER\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 2, in <module>
>     from sfast.compilers.stable_diffusion_pipeline_compiler import CompilationConfig
>   File "C:\Users\USER\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sfast\__init__.py", line 23, in <module>
>     import sfast._C as _C
> ImportError: DLL load failed while importing _C: The specified module could not be found.
> 
> Cannot import C:\Users\USER\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_stable_fast module for custom nodes: DLL load failed while importing _C: The specified module could not be found.
> ```

It's hard to debug on Windows. Usually this is caused by incompatible torch version, or missing cuda installation. Try WSL2 if you still cannot get it to work.

**Comment by NolenBrolen** [comment]
got it to work on Windows. I have multiple CUDA versions installed and 11.3 was added to path instead of 11.8. 
Also [this comment from a redditor](https://www.reddit.com/r/comfyui/comments/18f95yj/comment/kcud6b2/?context=3) replying to my question helped out a great deal, I indeed messed up with installing wrong torch versions
