### ISSUE TITLE
stable-fast version 1.0.0 does not support Windows system？

### ISSUE THREAD

**Issue by vbqgyy** [chengzeyi/stable-fast#92]
win10 system
installation environment：
triton==2.0.0
torch==2.1.0+cu118
xformers==0.0.22.post7+cu118
CUDA==11.8
Python==3.10.6

ComfyUI_stable_fast  
After updating the latest version：

Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 101, in apply_stable_fast
    config = gen_stable_fast_config()
  File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 22, in gen_stable_fast_config
    import triton
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\__init__.py", line 13, in <module>
    from . import language
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\language\__init__.py", line 2, in <module>
    from . import core, extern, libdevice, random
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\language\core.py", line 1141, in <module>
    def abs(x):
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 386, in jit
    return JITFunction(args[0], **kwargs)
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 315, in __init__
    self.run = self._make_launcher()
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 282, in _make_launcher
    scope = {"version_key": version_key(), "get_cuda_stream": get_cuda_stream,
  File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 82, in version_key    with open(triton._C.libtriton.__file__, "rb") as f:
AttributeError: partially initialized module 'triton' has no attribute '_C' (most likely due to a circular import)

**Comment by lengyanju8** [comment]
No module named 'sfast._C

**Comment by lengyanju8** [comment]
(py310) D:\sd\stable-fast>pip install -e .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///D:/sd/stable-fast
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\ProgramData\Anaconda3\envs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ProgramData\Anaconda3\envs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\ProgramData\Anaconda3\envs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rgx9b7up\overlay\Lib\site-packages\setuptools\build_meta.py", line 441, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rgx9b7up\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rgx9b7up\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rgx9b7up\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-rgx9b7up\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by lengyanju8** [comment]
C:\ProgramData\Anaconda3\envs\py310>python -m pip install D:\sd\stable-fast
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing d:\sd\stable-fast
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\ProgramData\Anaconda3\envs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ProgramData\Anaconda3\envs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\ProgramData\Anaconda3\envs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-f9lupbm6\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-f9lupbm6\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-f9lupbm6\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-f9lupbm6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by lengyanju8** [comment]
C:\ProgramData\Anaconda3\envs\py310>pip show torch
Name: torch
Version: 2.1.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\programdata\anaconda3\lib\site-packages
Requires: jinja2, fsspec, typing-extensions, networkx, sympy, filelock
Required-by: torchaudio, pytorch-wavelets, openai-whisper, accelerate

**Comment by chengzeyi** [comment]
@lengyanju8 Your `torch` is installed in a different python virtual env from `stable-fast`. You need to make sure that `torch` exists before `stable-fast`.

**Comment by chengzeyi** [comment]
> win10 system installation environment： triton==2.0.0 torch==2.1.0+cu118 xformers==0.0.22.post7+cu118 CUDA==11.8 Python==3.10.6
> 
> ComfyUI_stable_fast After updating the latest version：
> 
> Using xformers attention in VAE Working with z of shape (1, 4, 32, 32) = 4096 dimensions. Using xformers attention in VAE missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'} left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids']) ERROR:root:!!! Exception during processing !!! ERROR:root:Traceback (most recent call last): File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 101, in apply_stable_fast config = gen_stable_fast_config() File "D:\0AI\0StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_stable_fast\node.py", line 22, in gen_stable_fast_config import triton File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton__init__.py", line 13, in from . import language File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\language__init__.py", line 2, in from . import core, extern, libdevice, random File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\language\core.py", line 1141, in def abs(x): File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 386, in jit return JITFunction(args[0], **kwargs) File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 315, in **init** self.run = self._make_launcher() File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 282, in _make_launcher scope = {"version_key": version_key(), "get_cuda_stream": get_cuda_stream, File "D:\0AI\0StableDiffusion\ComfyUI\python_embeded\lib\site-packages\triton\runtime\jit.py", line 82, in version_key with open(triton._C.libtriton.**file**, "rb") as f: AttributeError: partially initialized module 'triton' has no attribute '_C' (most likely due to a circular import)

`triton` is currently not officially supported on Windows. Please disable it if you face problems.
